### ISSUE TITLE
please add the last coffee machine they got siemens ti909701hc

### ISSUE THREAD

**Issue by skandshus** [nlrb/com.home-connect#2]
is it possible to add the second coffee machine they have?

model siemens ti909701hc

if its a lot of work to get going id love to pay for it.

**Comment by nlrb** [comment]
Well, for this app to work an API key with full access is needed. But only partners get this (like Athom). However, the apps should work with any type of coffee machine that supports the home connect API.

**Comment by skandshus** [comment]
@nlrb 

i have tried adding the model to my devices in homey. but if i try to work with it. it fails everytime.. 

the device do support home connect. and it is working with alexas home connect app. and also with ifttt. but on Homey it does not work. since the model supported is the built in model (Siemens idCT836LEB6)

everytime i try any of the flow card it fails...

**Comment by nlrb** [comment]
I guess you refer to the Athom Home Connect app - not this one. This app is not in the app store and can only be used with simulators. Please report your issue to Athom.

**Comment by skandshus** [comment]
@nlrb oooohhh i see. so sorry
